name = "SubMatrixSelectionSVD"
uuid = "1e09ba94-8865-5af0-8cfd-6b3609c426e6"
authors = ["Rasmus Henningsson <rasmus.henningsson@gmail.com>", "Lund University"]
version = "0.1.1"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
